# Numpy
1. **Introduction to NumPy:** Start with an introduction to NumPy, explaining what it is and why it's used for numerical computations in Python.  
2. **Installation:** Guide on how to install NumPy using `pip`.  
3. **Creating Arrays:** Show how to create NumPy arrays from lists and with built-in functions like `np.zeros`, `np.ones`, and `np.arange`.  
4. **Array Operations:** Demonstrate basic array operations, including arithmetic operations, indexing, and slicing.  
5. **Reshaping and Transposing:** Explain how to reshape arrays using `np.reshape` and how to transpose arrays with `np.transpose`.  
6. **Statistical Functions:** Introduce statistical functions like `np.mean`, `np.median`, `np.var`, and how to use them on arrays.  
7. **Linear Algebra in NumPy:** Cover basic linear algebra operations, such as matrix multiplication using `np.matmul` and finding eigenvalues with `np.linalg.eig`.  
8. **Random Numbers:** Show how to generate random numbers and random arrays using NumPy's random module.  
9. **Filtering Arrays:** Teach how to filter arrays using boolean indexing.  
10. **Saving and Loading Arrays:** Conclude with how to save arrays to files using `np.save` and how to load them with `np.load`.

In [3]:
import numpy as np
arr = np.array([[0,1,2], [3,4,5]], dtype= np.float16)
#arr = np.array([1, 2, 3])
arr

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float16)

In [2]:
a = np.array([0,1])
b = np.array([9,8])
c = a
d = b.copy()
d[0] = 8
print(b)
print(d)

[9 8]
[8 8]


ranged data

In [3]:
arr = np.arange(3,12)
print(repr(arr))
print(arr)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])
[ 3  4  5  6  7  8  9 10 11]


In [11]:
arr = np.linspace(5,11, num=4)
print(arr)

[ 5.  7.  9. 11.]


Reshaping data

In [19]:
arr = np.arange(8)
reshaped_arr = np.reshape(arr[3:6], (1, 3))
print(reshaped_arr)

[[3 4 5]]


Transposing

In [21]:
arr = np.arange(8)
arr = np.reshape(arr, (4,2))
transposed = np.transpose(arr)
print(repr(arr))
print(repr(transposed))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])


Arithmetic

In [7]:
arr = np.array([[1, 2], [3, 4]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))

array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]], dtype=int32)
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


 Non-linear functions

In [8]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


 Matrix multiplication

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
# This will result in a ValueError: If we uncomment line 10 and run again.
#print(repr(np.matmul(arr3, arr3)))

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


Filtering in NumPy

In [10]:
print(repr(np.where([True, False, True])))

arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])
x_ind, y_ind = np.where(arr != 0)
print(repr(x_ind)) # x indices of non-zero elements
print(repr(y_ind)) # y indices of non-zero elements
print(repr(arr[x_ind, y_ind]))

(array([0, 2], dtype=int64),)
(array([1, 3], dtype=int64),)
array([0, 0, 1, 2], dtype=int64)
array([1, 2, 0, 0], dtype=int64)
array([ 2,  3,  1, -3])


**Statistics**

A. Analysis

In [11]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr.min())
print(arr.max())

print(repr(arr.min(axis=0)))

print(repr(arr.max(axis=-1)))

-60
72
array([ -3,  -2, -60])
array([72,  3,  4])


B. Statistical metrics

In [12]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(np.mean(arr))
print(np.var(arr))
print(np.median(arr))
print(repr(np.median(arr, axis=-1)))

2.0
977.3333333333334
1.0
array([ 3.,  1., -2.])


pandas

A. 1-D data#

In [13]:
import pandas as pd
import numpy as np
# Creating an empty series, will result in DeprecationWarning
#series = pd.Series()

# Passing dtype as a parameter to Series for an empty series to avoid DeprecationWarning
# Creating an empty series
series = pd.Series(dtype='float64')
# Newline to separate series print statements
print('{}\n'.format(series))

series = pd.Series(5)
print('{}\n'.format(series))

series = pd.Series([1, 2, 3])
print('{}\n'.format(series))

series = pd.Series([1, 2.2]) # upcasting
print('{}\n'.format(series))

arr = np.array([1, 2])
series = pd.Series(arr, dtype=np.float32)
print('{}\n'.format(series))

series = pd.Series([[1, 2], [3, 4]])
print('{}\n'.format(series))

Series([], dtype: float64)

0    5
dtype: int64

0    1
1    2
2    3
dtype: int64

0    1.0
1    2.2
dtype: float64

0    1.0
1    2.0
dtype: float32

0    [1, 2]
1    [3, 4]
dtype: object


 Index#

In [14]:
series = pd.Series(["raj","halder", "rohit"], index = [1,2,3])
print(series)

1       raj
2    halder
3     rohit
dtype: object


# **Random**

A. Random integers

In [15]:
import random

In [16]:
print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=14,
                               size=(2, 2))
print(repr(random_arr))

4
4
5
array([[-1,  1],
       [-3,  5]])


# **Indexing**

A. Array accessing#

In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

arr = np.array([[6, 3], [0, 2]])
# Subarray
print(repr(arr[0]))

1
5
array([6, 3])


B. **Slicing**

In [18]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


C. Argmin and argmax

In [19]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(np.argmin(arr[0]))
print(np.argmax(arr[2]))
print(np.argmin(arr))

2
1
5


Filtering

A. Filtering data

In [20]:
arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])
print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))
# Negated from the previous step
print(repr(~(arr != 1)))

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])
array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


# **Statistics**

A. Analysis

In [21]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr.min())
print(arr.max())

print(repr(arr.min(axis=0)))
print(repr(arr.max(axis=-1)))

-60
72
array([ -3,  -2, -60])
array([72,  3,  4])


B. Statistical metrics

NumPy also provides basic statistical functions such as np.mean, np.var, and np.median, to calculate the mean, variance, and median of the data, respectively.

The code below shows how to obtain basic statistics with NumPy. Note that np.median applied without axis takes the median of the flattened array.

In [22]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(np.mean(arr))

print(np.median(arr))
print(repr(np.median(arr, axis=-1)))

2.0
1.0
array([ 3.,  1., -2.])


B. Concatenation

In [23]:
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])
arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])
print(repr(np.concatenate([arr1, arr2])))
print(repr(np.concatenate([arr1, arr2], axis=1)))
print(repr(np.concatenate([arr2, arr1], axis=1)))

array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
array([[-15,   6,   1,   0,  72,   3],
       [  8,   9,  -4,   1,   3, -60],
       [  5, -21,  18,  -3,  -2,   4]])


Saving Data

A. Saving

In [24]:
arr = np.array([1, 2, 3])
# Saves to 'arr.npy'
np.save('arr.npy', arr)
# Also saves to 'arr.npy'
np.save('arr', arr)

B. Loading

In [25]:
arr = np.array([1, 2, 3])
np.save('arr.npy', arr)
load_arr = np.load('arr.npy')
print(repr(load_arr))

# Will result in a FileNotFoundError: If we uncomment line 7 and run again.
#load_arr = np.load('arr')

array([1, 2, 3])
