# Exercise Description
1. Array Creation and Properties:  
- Create a 2D array of shape (3, 4) filled with random integers between 10 and 50.
- Print the shape, size, and data type of the array.
2. Array Operations:  
- Calculate and print the sum of all elements in the array.
- Multiply every element in the array by 2 and print the new array.
3. Reshaping and Indexing:  
- Reshape the array into shape (4, 3).
- Access and print the second row of the reshaped array.
4. Statistical Analysis:  
- Find and print the mean and standard deviation of the original array.
- Determine the minimum and maximum values of the reshaped array.
5. Boolean Indexing:
- Create a boolean mask where True corresponds to elements greater than 25.
- Use the mask to filter out and print elements greater than 25 from the original array.

In [1]:
import numpy as np

# 1. Array Creation and Properties
array_2d = np.random.randint(10, 50, size=(3, 4))
print("Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data type:", array_2d.dtype)

# 2. Array Operations
print("Sum of all elements:", array_2d.sum())
print("Array elements multiplied by 2:\n", array_2d * 2)

# 3. Reshaping and Indexing
reshaped_array = array_2d.reshape(4, 3)
print("Reshaped array:\n", reshaped_array)
print("Second row of reshaped array:", reshaped_array[1])

# 4. Statistical Analysis
print("Mean:", array_2d.mean())
print("Standard deviation:", array_2d.std())
print("Minimum of reshaped array:", reshaped_array.min())
print("Maximum of reshaped array:", reshaped_array.max())

# 5. Boolean Indexing
mask = array_2d > 25
print("Elements greater than 25:", array_2d[mask])

Array:
 [[28 32 16 39]
 [13 44 38 34]
 [22 22 40 14]]
Shape: (3, 4)
Size: 12
Data type: int64
Sum of all elements: 342
Array elements multiplied by 2:
 [[56 64 32 78]
 [26 88 76 68]
 [44 44 80 28]]
Reshaped array:
 [[28 32 16]
 [39 13 44]
 [38 34 22]
 [22 40 14]]
Second row of reshaped array: [39 13 44]
Mean: 28.5
Standard deviation: 10.436314802968846
Minimum of reshaped array: 13
Maximum of reshaped array: 44
Elements greater than 25: [28 32 39 44 38 34 40]


1. Write a Python function to find the kth smallest element in a list.
2. Write a Python function to check if a list is a palindrome or not. Return true otherwise false.
3. Write a Python a function to implement a LRU cache.
From Wikipedia -
Least recently used (LRU)
Discards the least recently used items first. This algorithm requires keeping track of what was used when, which is expensive if one wants to make sure the algorithm always discards the least recently used item. General implementations of this technique require keeping "age bits" for cache-lines and track the "Least Recently Used" cache-line based on age-bits. In such an implementation, every time a cache-line is used, the age of all other cache-lines changes. LRU is actually a family of caching algorithms with members including 2Q by Theodore Johnson and Dennis Shasha, and LRU/K by Pat O'Neil, Betty O'Neil and Gerhard Weikum.
4. Write a Python function to reverse a list at a specific location.
5. Write a Python program to find all the pairs in a list whose sum is equal to a given value.

In [ ]:
 # Define a function to find the kth smallest element in a list
def kth_smallest_el(lst, k):
    # Sort the list in ascending order
    lst.sort()
    # Return the kth smallest element (0-based index, so k-1)
    return lst[k - 1]

# Create a list of numbers
nums = [1, 2, 4, 3, 5, 4, 6, 9, 2, 1]

# Print the original list
print("Original list:")
print(nums)

# Initialize 'k' to 1
k = 1

# Iterate from k = 1 to k = 10
for i in range(1, 11):
    # Print a message indicating the value of 'k'
    print("kth smallest element in the said list, when k =", k)

    # Call the kth_smallest_el function with 'k' and print the result
    print(kth_smallest_el(nums, k))

    # Increment 'k' by 1 for the next iteration
    k = k + 1


In [ ]:
# Define a function to check if a list is a palindrome (reads the same forwards and backwards)
def is_palindrome_list(lst):
    return lst == lst[::-1]

# Create a list of numbers
nums = [1, 2, 4, 3, 5, 4, 6, 9, 2, 1]

# Print the original list
print("Original list:")
print(nums)

# Print a message to check if the list is a palindrome or not
print("Check the said list is Palindrome or not?")

# Call the is_palindrome_list function and print the result
print(is_palindrome_list(nums))

# Create a second list of numbers that is a palindrome
nums = [1, 2, 2, 1]

# Print the original list
print("\nOriginal list:")
print(nums)

# Print a message to check if the list is a palindrome or not
print("Check the said list is Palindrome or not?")

# Call the is_palindrome_list function with the second list and print the result
print(is_palindrome_list(nums))

# Create a list of colors
colors = ["Red", "Green", "Blue"]

# Print the original list
print("\nOriginal list:")
print(colors)

# Print a message to check if the list is a palindrome or not
print("Check the said list is Palindrome or not?")

# Call the is_palindrome_list function with the colors list and print the result
print(is_palindrome_list(colors))

# Create another list of colors that is not a palindrome
colors = ["Red", "Green", "Red"]

# Print the original list
print("\nOriginal list:")
print(colors)

# Print a message to check if the list is a palindrome or not
print("Check the said list is Palindrome or not?")

# Call the is_palindrome_list function with the second colors list and print the result
print(is_palindrome_list(colors))  

In [ ]:
# Import the 'OrderedDict' class from the 'collections' module
from collections import OrderedDict

# Define a class 'LRUCache' for a Least Recently Used (LRU) cache
class LRUCache:
    # Initialize the LRUCache with a specified capacity
    def __init__(self, capacity: int):
        # Create an ordered dictionary 'cache' to store key-value pairs
        self.cache = OrderedDict()
        # Set the capacity of the cache
        self.capacity = capacity

    # Get the value associated with a key from the cache
    def get(self, key: int) -> int:
        # Check if the key is not in the cache
        if key not in self.cache:
            return -1
        else:
            # Move the accessed key to the end to mark it as most recently used
            self.cache.move_to_end(key)
            # Return the value associated with the key
            return self.cache[key]

    # Put a key-value pair into the cache
    def put(self, key: int, value: int) -> None:
        # Update the cache with the key-value pair
        self.cache[key] = value
        # Move the key to the end to mark it as most recently used
        self.cache.move_to_end(key)
        # Check if the cache size exceeds the specified capacity
        if len(self.cache) > self.capacity:
            # Remove the least recently used item (the first item) from the cache
            self.cache.popitem(last=False)

# Create an instance of the LRUCache class with a capacity of 2
cache = LRUCache(2)

# Put key-value pairs into the cache
cache.put(10, 10)
cache.put(20, 20)

# Get the value associated with key 10 from the cache
print(cache.get(10))   # 10

# Put another key-value pair into the cache, which causes the eviction of the least recently used item (key 20)
cache.put(30, 30)

# Get the value associated with key 20, which is not in the cache
print(cache.get(20))   # -1 

# Put another key-value pair into the cache, which causes the eviction of the least recently used item (key 10)
cache.put(40, 40)

# Get the value associated with key 10, which is not in the cache
print(cache.get(10))   # -1 

# Get the values associated with keys 30, and 40 from the cache
print(cache.get(30))   # 30
print(cache.get(40))   # 40 

In [ ]:
# Define a function to reverse a portion of a list in place
def reverse_list_in_location(lst, start_pos, end_pos):
    # Use a while loop to swap elements from the start and end positions
    while start_pos < end_pos:
        # Swap elements at start_pos and end_pos using tuple unpacking
        lst[start_pos], lst[end_pos] = lst[end_pos], lst[start_pos]
        # Move the start_pos towards the end_pos and vice versa
        start_pos += 1
        end_pos -= 1
    # Return the modified list
    return lst

# Create a list of numbers
nums = [10, 20, 30, 40, 50, 60, 70, 80]

# Define the start and end positions for the first reverse operation
start_pos = 2
end_pos = 4

# Print the original list
print("Original list:")
print(nums)

# Print a message indicating which portion of the list will be reversed
print("Reverse elements of the said list between index position " + str(start_pos) + " and " + str(end_pos))

# Call the reverse_list_in_location function and print the result
print(reverse_list_in_location(nums, start_pos, end_pos))

# Define the start and end positions for the second reverse operation
start_pos = 6
end_pos = 7

# Print a message indicating which portion of the list will be reversed
print("\nOriginal list:")
print(nums)
print("Reverse elements of the said list between index position " + str(start_pos) + " and " + str(end_pos))

# Call the reverse_list_in_location function again and print the result
print(reverse_list_in_location(nums, start_pos, end_pos))

# Define the start and end positions for the third reverse operation
start_pos = 0
end_pos = 7

# Print a message indicating which portion of the list will be reversed
print("\nOriginal list:")
print(nums)
print("Reverse elements of the said list between index position " + str(start_pos) + " and " + str(end_pos))

# Call the reverse_list_in_location function once more and print the result
print(reverse_list_in_location(nums, start_pos, end_pos)) 

In [ ]:
# Define a function to find all pairs in a list that sum up to a given value
def pairs_with_sum(lst, g_sum):
    # Create an empty dictionary 'complement_dict' to store complements of visited numbers
    complement_dict = {}
    # Create an empty list 'pairs' to store the pairs that sum up to the target value
    pairs = []
    # Iterate through the elements in the input list 'lst'
    for num in lst:
        # Calculate the complement of the current number with respect to the target value
        complement = g_sum - num
        # Check if the complement is already in 'complement_dict'
        if complement in complement_dict:
            # If found, add the current number and its complement as a pair to 'pairs'
            pairs.append((num, complement))
        else:
            # If not found, store the complement in 'complement_dict' for future checks
            complement_dict[num] = complement
    # Return the list of pairs that sum up to the target value
    return pairs

# Create a list of numbers
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9]
# Set a target sum 'val'
val = 10

# Print the original list of numbers
print("Original list:")
print(nums)

# Call the pairs_with_sum function with the list of numbers and the target sum 'val', and store the result in 'result'
result = pairs_with_sum(nums, val)

# Print the result, which is a list of pairs that sum up to 'val'
print("List all pairs of the said list whose sum equals to", val)
print(result)

# Update the target sum 'val'
val = 35

# Print the original list of numbers
print("\nOriginal list:")
print(nums)

# Call the pairs_with_sum function with the updated target sum 'val' and the same list of numbers, and store the result in 'result'
result = pairs_with_sum(nums, val)

# Print the result, which is a list of pairs that sum up to the updated 'val'
print("List all pairs of the said list whose sum equals to", val)
print(result)

# Update the target sum 'val' again
val = 5

# Print the original list of numbers
print("\nOriginal list:")
print(nums)

# Call the pairs_with_sum function with the updated target sum 'val' and the same list of numbers, and store the result in 'result'
result = pairs_with_sum(nums, val)

# Print the result, which is a list of pairs that sum up to the updated 'val'
print("List all pairs of the said list whose sum equals to", val)
print(result) 
